# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionTime', models.DateTimeField(auto_now=True, verbose_name='QuestionTime')),
                ('QuestionAuthor', models.CharField(blank=True, max_length=255, unique=True, verbose_name='QuestionAuthor')),
                ('QuestionTitle', models.CharField(blank=True, max_length=255, unique=True, verbose_name='QuestionTitle')),
                ('QuestionSupply', models.CharField(max_length=1000, verbose_name='QuestionSupply')),
                ('QuestionBody', models.TextField(max_length=2000, verbose_name='QuestionBody')),
            ],
            options={
                'ordering': ['QuestionTime'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerAuthor', models.CharField(blank=True, max_length=255, unique=True, verbose_name='')),
                ('AnswerTime', models.DateTimeField()),
                ('AnswerBody', models.CharField(max_length=1000)),
                ('Question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdemo.Bbs')),
            ],
            options={
                'ordering': ['AnswerTime'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
