# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.TimeField(help_text='输入有误2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.TimeField(help_text='输入有误'),
        ),
    ]
