# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='AnswerAuthor',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='AnswerAuthor: '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='AnswerBody',
            field=models.CharField(max_length=1000, verbose_name='AnswerBody: '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='AnswerTime',
            field=models.DateTimeField(auto_now=True, verbose_name='AnswerTime: '),
        ),
    ]
