# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0002_auto_20160817_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='AnswerAuthor',
            field=models.CharField(blank=True, max_length=255, verbose_name='AnswerAuthor: '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='AnswerBody',
            field=models.TextField(max_length=1000, verbose_name='AnswerBody: '),
        ),
    ]
