# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0002_auto_20160831_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='QuestionType',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='QuestionType'),
        ),
    ]
