# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0002_auto_20160805_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateField(help_text='输入有误'),
        ),
    ]
