# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0004_auto_20160902_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='QuestionScore',
            field=models.CharField(blank=True, max_length=255, verbose_name='QuestionScore'),
        ),
    ]
