# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0005_bbs_questionscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='QuestionScore',
            field=models.IntegerField(blank=True, default=0, max_length=255, verbose_name='QuestionScore'),
        ),
    ]
