# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0005_auto_20160809_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='QuestionBody',
            field=models.TextField(max_length=2000, verbose_name='QuestionBody'),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='QuestionSupply',
            field=models.CharField(max_length=1000, verbose_name='QuestionSupply'),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='QuestionTitle',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='QuestionTitle'),
        ),
    ]
