# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdemo', '0006_auto_20160902_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='QuestionScore',
            field=models.IntegerField(blank=True, default=0, verbose_name='QuestionScore'),
        ),
    ]
